Repository prgrms-web-devcourse-final-project/WEB2_3_SIGNAL-BUDDY_FE, pull requests merged in 2025-02, with the labels that each got.

#4 [merge / 3-feat-add-logo-image-to-readmemd]✨feat: README.md 파일에 미리보기 이미지 추가
  README.md
Labels: enhancement

#6 [merge / 5-feat-initialize-project-file] 🎉 Kickoff: 불필요 파일 삭제 및 프로젝트 파일 초기화
  .eslintrc.json
  package.json
  prettier.config.js
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
  tsconfig.json
  yarn.lock
Labels: documentation

#7 [merge / 5-feat-initialize-project-file] 🎨 add: zustand, tanstack query 설치
  package.json
  yarn.lock
Labels: documentation

#8 [merge / dev] 초기 개발 환경 배포
  .eslintrc.json
  .vscode/settings.json
  README.md
  package.json
  prettier.config.js
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
  tsconfig.json
  yarn.lock
Labels: good first issue

#12 [merge / 11-feat-initial-routing] ✨ feat: 페이지 라우팅
  src/app/(with-title)/join/page.tsx
  src/app/(with-title)/layout.tsx
  src/app/(with-title)/login/page.tsx
  src/app/admin/feedback/page.tsx
  src/app/admin/layout.tsx
  src/app/admin/page.tsx
  src/app/admin/postits/page.tsx
  src/app/admin/reports/page.tsx
  src/app/admin/terms/page.tsx
  src/app/admin/users/page.tsx
  src/app/directions/page.tsx
  src/app/feedback/[id]/edit/page.tsx
  src/app/feedback/[id]/page.tsx
  src/app/feedback/page.tsx
  src/app/feedback/write/page.tsx
  src/app/my-page/my-postits/page.tsx
  src/app/my-page/page.tsx
  src/app/my-page/profile/page.tsx
  src/app/my-page/settings/page.tsx
  src/app/my-place/edit/page.tsx
  src/app/my-place/layout.tsx
  src/app/my-place/page.tsx
Labels: enhancement

#13 [merge / 10-feat-pwa-initial-setup] ✨ feat: PWA 초기설정 및 manifest 파일 추가, 최상단 레이아웃 구분
  next.config.ts
  package-lock.json
  package.json
  public/icon-192x192.png
  public/icon-512x512.png
  public/sw.js
  src/app/actions.ts
  src/app/layout.tsx
  src/app/manifest.ts
  src/app/page.tsx
  src/components/footer/Footer.tsx
  src/components/nav/Navbar.tsx
  yarn.lock
Labels: enhancement

#16 [merge / 14-feat-implement-navigation-bar] ✨ feat: 상단바, 하단 푸터 구현
  public/imgs/Logo Symbol.png
  public/imgs/Logo.png
  src/app/layout.tsx
  src/app/map/page.tsx
  src/components/footer/Footer.tsx
  src/components/nav/Navbar.tsx
  tailwind.config.ts
  tsconfig.json
Labels: enhancement

#18 [merge / 17-style-landing-page-publish]💄 style: 랜딩 페이지 반응형 UI 구현
  components.json
  components/ui/button.tsx
  lib/utils.ts
  next.config.ts
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/footer/Footer.tsx
  src/components/nav/Navbar.tsx
  tailwind.config.ts
  yarn.lock
Labels: enhancement

#20 [merge / 19-style-mypage-publising]💄 style: 마이페이지 UI 구현
  public/imgs/liked-feedback.svg
  public/imgs/liked-postit.svg
  public/imgs/my-feedback.svg
  public/imgs/my-postit.svg
  src/app/my-page/profile-edit/page.tsx
  src/app/my-page/profile/page.tsx
Labels: enhancement

#29 [merge /style-map] 지도 페이지 레이아웃 및 기능 구현
  components/ui/form.tsx
  package.json
  prettier.config.js
  public/imgs/current-marker.png
  public/sw.js
  public/workbox-1bb06f5e.js
  src/app/(user)/(map)/map/page.tsx
  src/app/(user)/layout.tsx
  src/app/layout.tsx
  src/components/login-form/login-form.tsx
  src/components/map/MapBox.tsx
  src/components/map/MapSearch.tsx
  src/components/map/Marker.tsx
  src/constants/index.ts
  src/constants/map.ts
  src/hooks/useGeoLocation.ts
  src/hooks/useMap.ts
  src/types/global.d.ts
  src/types/index.ts
  src/types/tmap.ts
  src/utils/index.ts
  src/utils/reactElementToString.ts
  yarn.lock
Labels: enhancement

#34 [merge / 33-bug-yarnpakage-error] hotfix: 빌드 문제 해결
  package.json
  public/sw.js
  src/app/actions.ts
  yarn.lock
Labels: bug

#35 [merge / dev] 🔖 release: 멘토링용 중간 작업 내용 배포
  package.json
  public/sw.js
  src/app/actions.ts
  yarn.lock
Labels: documentation

#39 [merge / 38-style-feedback-details-publishing]💄 style: 피드백 상세페이지 퍼블리싱
  next.config.ts
  src/app/(user)/(service)/feedback/[id]/page.tsx
  src/components/feedback/FeedbackCommentList.tsx
  src/components/feedback/MeatballMenu.tsx
  src/components/utils/icons.tsx
  src/types/feedback.d.ts
Labels: enhancement

#42 [merge / dev] 지도 앱 테스트용 배포
  components/ui/breadcrumb.tsx
  components/ui/drawer.tsx
  components/ui/dropdown-menu.tsx
  next.config.ts
  package.json
  public/imgs/click-marker.png
  public/imgs/click-poi-marker.png
  public/imgs/poi-marker.png
  src/app/(user)/(map)/layout.tsx
  src/app/(user)/(map)/map/page.tsx
  src/app/(user)/(service)/feedback/[id]/page.tsx
  src/app/(user)/(service)/layout.tsx
  src/app/(user)/layout.tsx
  src/app/layout.tsx
  src/components/feedback/FeedbackCommentList.tsx
  src/components/feedback/MeatballMenu.tsx
  src/components/footer/Footer.tsx
  src/components/map/MapBox.tsx
  src/components/map/MapButtons.tsx
  src/components/map/MapSearch.tsx
  src/components/utils/icons.tsx
  src/hooks/useGeoLocation.ts
  src/types/feedback.d.ts
  src/types/global.d.ts
  src/types/tmap.ts
  yarn.lock
Labels: enhancement

#44 [merge / 37 style my place publishing] 💄 style: my place 페이지 퍼블리싱
  package.json
  public/imgs/Delete.svg
  public/imgs/two-line-hamburger.svg
  src/app/(user)/(service)/my-place/edit/page.tsx
  src/app/(user)/(service)/my-place/layout.tsx
  src/app/(user)/(service)/my-place/page.tsx
  src/components/my-place/MyPlaceData.ts
  src/components/my-place/MyPlaceList.tsx
  src/components/my-place/MyPlaceListEdit.tsx
  yarn.lock
Labels: enhancement

#56 [merge / 50-feat-add-react-query-settings] ✨ react-query 설정 및 피드백 화면 API 연결
  components/ui/sidebar.tsx
  components/ui/toggle-group.tsx
  package.json
  src/app/(user)/(service)/feedback/page.tsx
  src/app/layout.tsx
  src/components/feedback/FeedbackList.tsx
  src/components/feedback/FeedbackSearchbar.tsx
  src/components/feedback/FeedbackSidebar.tsx
  src/components/map/MapButtons.tsx
  src/components/shadcn/components/ui/toggle-group.tsx
  src/components/utils/QueryProvider.tsx
  src/contexts/RootProvider.tsx
  src/store/feedback/useFeedbakList.ts
  src/types/feedback.d.ts
  src/utils/formatDate.ts
  tailwind.config.ts
  yarn.lock
Labels: enhancement

#59 [merge / 57-feat-next-auth-featured] ✨ Feat. user 정보
  src/auth.ts
  src/types/next-auth.d.ts
Labels: enhancement

#62 [merge / 47 feat 로그인 기능 구현] refactor: 비밀번호 재설정 코드 정리 및 비밀번호 미리보기 기능 추가
  public/imgs/eye-open.svg
  public/imgs/eye-slash.svg
  src/app/(user)/(service)/(auth)/layout.tsx
  src/app/(user)/(service)/(auth)/reset-password/page.tsx
  src/app/(user)/(service)/(auth)/reset-password/reset/page.tsx
  src/app/(user)/(service)/(auth)/reset-password/verify/page.tsx
  src/components/auth/join-form/join-form.tsx
  src/components/auth/login/login-form.tsx
  src/components/auth/password-input.tsx
  src/components/auth/reset-password/OTP-form.tsx
  src/components/auth/reset-password/email-form.tsx
  src/components/auth/reset-password/reset-password-verification.tsx
  src/components/auth/reset-password/reset-password.tsx
  src/components/auth/reset-password1/reset-password1.tsx
  src/components/auth/reset-password2/reset-password2.tsx
  src/components/auth/reset-password3/reset-password3.tsx
Labels: enhancement
